# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import datetime
sys.path.insert(0, os.path.abspath('.'))


# -- Git information -----------------------------------------------------

import git
from etc.settings import GIT_VERSION, GIT_REVISION, LOGO_DIR

LATEX_LOGO_DIR=LOGO_DIR + '/'

#
# -- Project information -----------------------------------------------------

project = '{{ values.project }}'
copyright = '{{ values.copyright }}'

{% if values.language ==  'en' %}
author = '{{ values.author }}'
{% else %}
author = '{{ values.author }}'
{% endif %}

# The short X.Y version
version = GIT_VERSION
# The full version, including alpha/beta/rc tags
release = datetime.datetime.now().strftime('%B %Y')
releasename = 'Version'

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
if os.path.basename(os.path.dirname(  os.path.dirname( os.path.abspath(__file__)  ) )) == 'pdf_conf' :
    extensions = [
        'sphinx.ext.autodoc',
        'sphinx.ext.intersphinx',
        'sphinx.ext.imgmath', # for pdf creation only
        'sphinx.ext.ifconfig',
        'sphinx.ext.graphviz',
        'sphinxcontrib.bibtex'] 
else :
    extensions = [
        'sphinx.ext.autodoc',
        'sphinx.ext.intersphinx',
        'sphinx.ext.mathjax',
        'sphinx.ext.ifconfig',
        'sphinx.ext.graphviz',
        'sphinxcontrib.bibtex'] 

numfig=True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '{{ values.suffix }}'

# The master toctree document.
master_doc = '{{ values.master }}'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = '{{ values.language }}'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'sticky_navigation': True,
    }

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_copy_source = False
html_show_sourcelink = False

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.

htmlhelp_basename = '{{ values.project_fn }}'

# -- Options for LaTeX output ------------------------------------------------
if language == 'en':
    latex_preamble = r'''

\usepackage{graphicx}
\usepackage[T1]{fontenc}
\usepackage[version=3]{mhchem}
\usepackage{shadow}
\usepackage{amsmath, units, cancel}
\usepackage{amsfonts, amssymb,color}
\usepackage{multicol,pifont,mdframed,lscape}
\usepackage{nicefrac,marvosym,wasysym, textcomp, gensymb}
\usepackage[style=english]{csquotes}
\usepackage{charter}
\usepackage[defaultsans]{lato}
\usepackage{inconsolata}
\setlength{\headheight}{16pt}
\setcounter{secnumdepth}{-1}
\setcounter{tocdepth}{2}
\usepackage{hyperref,url}
\usepackage{float}
\usepackage{chemfig}
\usepackage[printwatermark]{xwatermark}
\usepackage{xcolor}
{% if values.draft %}
\usepackage{tikz}
{% endif %}

\watermarkpaths*{ ./, %s , }

\newwatermark*[ oddpages, picangle=0,
  picontoptext=true,boxalign=left,
  picbb=0 0 300 50 ,picscale=0.4,picfile=sphinx,
  picfileext=png,picxpos=-80,picypos=136
]{}

\newwatermark*[ evenpages, picangle=0,
  picontoptext=true,boxalign=right,
  picbb=0 0 300 50 ,picscale=0.4,picfile=sphinx,
  picfileext=png,picxpos=80,picypos=136
]{}

{% if values.draft %}

\newsavebox\mybox
\savebox\mybox{\tikz[color=red,opacity=0.3]\node{DRAFT};}
\newwatermark*[
  pages=1-3,
  angle=45,
  scale=6,
  xpos=-20,
  ypos=15
]{\usebox\mybox}

{% endif %}

\hypersetup{
pdftitle={% raw %}{{% endraw %}{{ values.project }}{% raw %}}{% endraw %},
pdfsubject={% raw %}{{% endraw %}{{ values.project }}{% raw %}}{% endraw %},
pdfauthor={% raw %}{{% endraw %}{{ values.author }}{% raw %}}{% endraw %},
pdfcreator={% raw %}{{% endraw %}{{ values.author }}{% raw %}}{% endraw %},
pdfproducer={Sphinx-Gitlab-Quickstart},
pdfkeywords={Sphinx} {Gitlab} {Quickstart} {Gitlab CI},
}
'''%(LATEX_LOGO_DIR)
else:
        latex_preamble = r'''

\usepackage{graphicx}
\usepackage[T1]{fontenc}
\usepackage[version=3]{mhchem}
\usepackage{shadow}
\usepackage{amsmath, units, cancel}
\usepackage{amsfonts, amssymb,color}
\usepackage{multicol,pifont,mdframed,lscape}
\usepackage{nicefrac,marvosym,wasysym, textcomp, gensymb}
\usepackage[style=german]{csquotes}
\usepackage{charter}
\usepackage[defaultsans]{lato}
\usepackage{inconsolata}
\setlength{\headheight}{16pt}
\setcounter{secnumdepth}{-1}
\setcounter{tocdepth}{2}
\usepackage{hyperref,url}
\usepackage{float}
\usepackage{chemfig}
\usepackage[printwatermark]{xwatermark}
\usepackage{xcolor}
{% if values.draft %}
\usepackage{tikz}
{% endif %}

\watermarkpaths*{ ./, %s , }

\newwatermark*[ oddpages, picangle=0,
  picontoptext=true,boxalign=left,
  picbb=0 0 300 50 ,picscale=0.4,picfile=sphinx,
  picfileext=png,picxpos=-80,picypos=136
]{}

\newwatermark*[ evenpages, picangle=0,
  picontoptext=true,boxalign=right,
  picbb=0 0 300 50 ,picscale=0.4,picfile=sphinx,
  picfileext=png,picxpos=80,picypos=136
]{}

{% if values.draft %}

\newsavebox\mybox
\savebox\mybox{\tikz[color=red,opacity=0.3]\node{ENTWURF};}
\newwatermark*[
  pages=1-3,
  angle=45,
  scale=6,
  xpos=-20,
  ypos=15
]{\usebox\mybox}

{% endif %}

\hypersetup{
pdftitle={% raw %}{{% endraw %}{{ values.project }}{% raw %}}{% endraw %},
pdfsubject={% raw %}{{% endraw %}{{ values.project }}{% raw %}}{% endraw %},
pdfauthor={% raw %}{{% endraw %}{{ values.author }}{% raw %}}{% endraw %},
pdfcreator={% raw %}{{% endraw %}{{ values.author }}{% raw %}}{% endraw %},
pdfproducer={Sphinx-Gitlab-Quickstart},
pdfkeywords={Sphinx} {Gitlab} {Quickstart} {Gitlab CI},
}
'''%(LATEX_LOGO_DIR)

latex_show_pagerefs = False
imgmath_image_format='png'
imgmath_latex_preamble = latex_preamble

if language == 'en' :
    latex_elements = {
        'preamble': latex_preamble,
        'classoptions': 'oneside,openany',
        'releasename': "Version",
        'papersize': 'a4paper',
        'pointsize': '11pt',
        'fontpkg': '',
        'babel':    '\\usepackage[english]{babel}',
        'geometry': '\\usepackage[left=2.5cm, right=2.5cm, top=2.5cm, bottom=2.5cm]{geometry}',
        'fncychap': '',
        'figure_align': 'H',
    
    }
else :
    latex_elements = {
        'preamble': latex_preamble,
        'classoptions': 'oneside,openany',
        'releasename': "Version",
        'papersize': 'a4paper',
        'pointsize': '11pt',
        'fontpkg': '',
        'babel':    '\\usepackage[ngerman]{babel}',
        'geometry': '\\usepackage[left=2.5cm, right=2.5cm, top=2.5cm, bottom=2.5cm]{geometry}',
        'fncychap': '',
        'figure_align': 'H',
    
    }

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, '{{ values.project_fn }}.tex', u'{{ values.project }}',
     u'{{ values.author }}', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, '{{ values.project_fn }}', u'{{ values.project }}',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, '{{ values.project_fn }}', u'{{ values.project }}',
     author, '{{ values.project_fn }}', '{{ values.one_line_desc }}',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/': None}
